node:
  name: test-mysql01
mysql:
  user:
  password:
  host:
  port: 3306
  name: performance_schema
logpath:
  path:
heartbeat:
  interval: 5
  downcommand:
    - ll
    - ls
  upcommand:
    - ll
    - ls